name: Yeet
main: hypepixel.yeet.main.Yeet
version: 1.0.0
api-version: 1.15
author: Hypepixel
description: The player gets a reward for yeeting.
permissions:
      yeet.commands.yeet:
        description: Allows yeet command
        default: true
      yeet.*:
        description: Wildcard permission
        default: false
        children:
          yeet.commands.yeet: true
commands:
   yeet:
      description: Give a diamond
      permission: yeet.commands.yeet
      permission-message: You do not have permission!
      usage: /yeet
     